logging:
  level: 'DEBUG'
http_port: 8080
http_host: '0.0.0.0'
backends:
  - name: resources.ovirt.org
    remote_path: '/srv/resources/pub'
    max_stamp: 20
    dirs:
      - 'ovirt-master-snapshot'
      - 'ovirt-master-snapshot-static/src/mingw-spice-vdagent'
      - 'ovirt-4.0/src'
    stamp_interval: 60.0
    ts_fname: '.timestamp'
    ssh_args:
       key_filename: '/mirrorchecker/id_rsa'
       hostname: 'resources.ovirt.org'
       timeout: 3.0
    yum_request: 'yum/mirrorlist-ovirt-{version}-{dist}'
    yum_response: 'ovirt-{version}/rpm/{dist}/'
    yum_threshold: 43200
    http_prefix: '/mirrors'
    mirrors_file: '/mirrorchecker/mirrors.txt'
